language: python

python:
  - '3.5'
    
before_script:
  - pip3 install sqflint

script:
  - python3 tools/sqf_validator.py
  - python3 tools/config_style_checker.py
  - sqflint -d addons/vana_loadoutmanagement

notifications:
  email:
    on_success: never
    on_failure: change
