language: python

python:
  - '3.5'
  
branches:
  only:
    - master
    
before_script:
  - pip3 install sqflint

script:
  - python3 tools/sqf_validator.py
  - python3 tools/config_style_checker.py
  - sqflint -d addons/VANA_LoadoutManagement

notifications:
  email:
    on_success: never
    on_failure: change
